#!/bin/sh

if [ $1 = "tayne" ]; then
    dancer=$1
    frames=23
    seconds=0.06
else
    dancer="celery"
    frames=45
    seconds=0.03
fi

i=1
while true; do
    if [ ${#i} -eq 2 ]; then
        cat "$dancer/$i.txt"
    else
        cat "$dancer/0$i.txt"
    fi

    sleep $seconds
    clear

    i=`expr $i + 1`

    if [ $i -eq $frames ]; then
        i=1
    fi
done
